# Generated by Django 3.2.5 on 2021-07-13 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(blank=True, max_length='200')),
                ('customer_id', models.TextField(blank=True, max_length='50')),
                ('customer_phone', models.TextField(blank=True, max_length='50')),
                ('customer_email', models.TextField(blank=True, max_length='50')),
                ('vehicle_number', models.TextField(blank=True, max_length='50')),
                ('vehicle_name', models.TextField(blank=True, max_length='50')),
                ('vehicle_documents', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Key_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.TextField(blank=True, max_length='100')),
            ],
        ),
        migrations.CreateModel(
            name='slots_booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.TextField(blank=True, max_length='100')),
                ('Slot_duration', models.TextField(blank=True, max_length='50')),
                ('customer_info', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='parking_spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.TextField(blank=True, max_length='100')),
                ('space_address', models.TextField(blank=True, max_length='1000')),
                ('total_slots', models.IntegerField(blank=True)),
                ('slot_monthly_rates', models.IntegerField(blank=True)),
                ('slot_hourly_rates', models.IntegerField(blank=True)),
                ('key_words', models.ManyToManyField(blank=True, to='dashboard.Key_table')),
                ('slot_booking', models.ManyToManyField(blank=True, to='dashboard.slots_booking_table')),
            ],
        ),
    ]
