# Generated by Django 3.2.5 on 2021-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vehicle_color',
            field=models.TextField(blank=True, max_length='50'),
        ),
    ]
