# Generated by Django 3.2.5 on 2021-07-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_parking_spaces_spcae_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking_spaces',
            old_name='spcae_name',
            new_name='spcae_pic',
        ),
    ]
