# Generated by Django 3.2.5 on 2021-07-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_spcae_name_parking_spaces_spcae_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vehicle_documents',
            field=models.FileField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
