# Generated by Django 3.2.5 on 2021-07-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_customer_vehicle_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vehicle_documents',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
