# Generated by Django 3.2.5 on 2021-07-16 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_alter_customer_vehicle_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_spaces',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle_documents',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
