# Generated by Django 3.2.5 on 2021-07-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210716_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking_spaces',
            name='user',
        ),
        migrations.AlterField(
            model_name='slots_booking_table',
            name='customer_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
    ]
