# Generated by Django 3.2.5 on 2021-07-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='from_date',
            field=models.TextField(blank=True, max_length='10000'),
        ),
        migrations.AddField(
            model_name='temp',
            name='to_data',
            field=models.TextField(blank=True, max_length='10000'),
        ),
    ]
