# Generated by Django 3.2.5 on 2021-07-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210718_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='from_date_tem',
            field=models.TextField(blank=True, max_length='10000'),
        ),
    ]
