# Generated by Django 3.2.5 on 2021-07-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210719_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='vehicle_documents',
        ),
    ]
