# Generated by Django 3.2.5 on 2021-07-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_customer_vehicle_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vehicle_documents',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='slots_booking_table',
            name='total_price',
            field=models.TextField(blank=True, max_length='100'),
        ),
    ]
