# Generated by Django 3.2.5 on 2021-07-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210719_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots_booking_table',
            name='slot_name',
        ),
    ]
