# Generated by Django 3.2.5 on 2021-07-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_slots_booking_table_slot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots_booking_table',
            name='slot_name',
            field=models.TextField(blank=True, max_length='100'),
        ),
    ]
