# Generated by Django 3.2.5 on 2021-07-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_slots_booking_table_slot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots_booking_table',
            name='slot_name',
        ),
    ]
